# Generated by Django 3.0.4 on 2020-09-04 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=150, verbose_name='Статус')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(max_length=15, verbose_name='Номер телефона')),
                ('name', models.CharField(max_length=70, verbose_name='ФИ клиента')),
                ('number', models.CharField(max_length=150, verbose_name='Код Заказа')),
                ('brand', models.CharField(max_length=300, verbose_name='Бренд')),
                ('articul', models.CharField(max_length=150, verbose_name='Артикул')),
                ('term', models.DateField(max_length=150, verbose_name='Дата заказа')),
                ('term_wanted', models.DateField(verbose_name='Ожидается на складе')),
                ('amount_wanted', models.IntegerField(verbose_name='Было заказано')),
                ('amount_actual', models.IntegerField(verbose_name='Количество')),
                ('cost', models.FloatField(verbose_name='Цена за штуку')),
                ('pre_cost', models.FloatField(verbose_name='Предоплата')),
                ('description', models.TextField(verbose_name='Описание')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Status')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
