# Generated by Django 3.0.4 on 2020-09-04 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(default='', max_length=70, verbose_name='ФИ клиента'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pre_cost',
            field=models.FloatField(default='', verbose_name='Предоплата'),
        ),
        migrations.AlterField(
            model_name='order',
            name='telephone',
            field=models.CharField(default='', max_length=15, verbose_name='Номер телефона'),
        ),
    ]
